### ISSUE TITLE
It does not work on windows

### ISSUE THREAD

**Issue by Hemingway2003** [sjemens/qsqlcipher-qt5#13]
So where is `QSqlDriverPrivate`?

**Comment by sjemens** [comment]
Which Qt version you are using? Select the same branch from the repo.

**Comment by Hemingway2003** [comment]
Qt 5.14.2

**Comment by Hemingway2003** [comment]
But the basic thing is: there is no `qmake` in windows platform

**Comment by sjemens** [comment]
You can find qmake in the qt installation command line

![1-qt-shortcut](https://user-images.githubusercontent.com/6699118/156815291-74aaca96-6821-4897-9f51-d87bc4b1f2c0.png)

![2-qt-cli](https://user-images.githubusercontent.com/6699118/156814334-2e055e4e-0e50-402d-9ad4-1d18d74f6f2e.png)

Of course you should see your qt version.
If your using Visual C++ compiler complete the environment setup  by running `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"` and remember to use `nmake` instead of `make`

...or if you have no experience of the command line, use Qt Creator in pretty much the standard way you build a project.

**Comment by Hemingway2003** [comment]
Thanks for your replying.
There were errors in the `command line`:
![image](https://user-images.githubusercontent.com/16931525/156962321-89a1a7b0-76c9-406f-9da2-efeeda1ffcc1.png)
And also errors in qt creator:
![image](https://user-images.githubusercontent.com/16931525/156962387-72d3481d-5ae9-42d1-a4f7-dbab1203d71e.png)
And I have build sqlcipher.dll my self, so you could try to build this project on a windows platform -- if you really want this project as a reference
