### ISSUE TITLE
Can you explain where SQLCipher used in source code?

### ISSUE THREAD

**Issue by tr1cks** [sjemens/qsqlcipher-qt5#2]
I very appreciate your work, but can't figure out by one sight where SQLCipher comes to work.

**Comment by sjemens** [comment]
The main difference from the official QSQLITE plugin is the linking with the sqlcipher library. This happens in [qsqlcipher.pro](https://github.com/sjemens/qsqlcipher-qt5/blob/master/qsqlcipher/qsqlcipher.pro). Secondary, in [main.cpp](https://github.com/sjemens/qsqlcipher-qt5/blob/master/qsqlcipher/smain.cpp) I named the plugin as to not conflict with the qsqlite naming. To enable the encryption capabilities one should use the PRAGMA options as are documented in the [sqlipher API](https://www.zetetic.net/sqlcipher/sqlcipher-api/). You can see the most basic use cases in the [tests](https://github.com/sjemens/qsqlcipher-qt5/blob/master/tests/main.cpp)

**Comment by tr1cks** [comment]
Thanks for clarification. Now I understood that sqlcipher is drop-in-replacement library.

Can you specify what versions of openssl and sqlcipher was used? I trying to build them for iOS and Mac OS right now.

**Comment by sjemens** [comment]
@tr1cks 
I see that you have forked the android branch so I guess you are asking what versions are the static libs. Openssl is version 1.1.1a and sqlcipher is version 4.0.1. (In desktop I am always using the system libraries and since I am using Arch Linux these are always the latest versions.)
I think you should modify the build scripts for [openssl](https://github.com/sjemens/sqlcipher/blob/android/build-openssl-libraries.sh) and [sqlcipher](https://github.com/sjemens/sqlcipher/blob/android/build-sqlcipher.sh) to build your libraries. However I am sorry to say that I never programmed for iOS and Mac OS, so I am not sure if I  can offer any more assistance there.

**Comment by tr1cks** [comment]
@sjemens 
I added support for iOS and Mac OS in my fork. I prefer to use OpenSSL, but other option is platform encryption API.
