### ISSUE TITLE
The SQLCipher headers and libraries should be installed before compiling this plugin

### ISSUE THREAD

**Issue by joenano** [sjemens/qsqlcipher-qt5#3]
any chance of linking to them? you know, the exact dependencies your project needs to work....

**Comment by sjemens** [comment]
Just to be clear, do you suggest that I should provide precompiled binaries from sqlcipher? If not then I guess the following answer wouldn't make much sense, but here I go.

The short answer is: I could, but I will not.

The medium answer: See this experimental [branch here](https://github.com/sjemens/qsqlcipher-qt5/tree/exp) that includes all dependencies in a 3rdparty folder as source. No precompiled binaries included.

The long answer: Most linux distributions provide those headers and libraries through their package manager. This could be a single package as is the case in ArchLinux, or as a combination of lib, -dev as in Debian and derivatives. Package managers can do a better job than me to keep the dependencies up to date.

In case of windows, personally I use mingw through [MSYS2](https://github.com/msys2/MINGW-packages), which offers both i386 and x86_64 versions of sqlcipher again through its package manager. Also for mingw there is the options to cross compile. This is how it is done for example in a package I wrote for [archlinux](https://aur.archlinux.org/packages/mingw-w64-sqlcipher/).

For windows with MSVC compiler it is a bit harder to build the library but not impossible. One way is explained in my fork of sqlcipher on [msvc branch](https://github.com/sjemens/sqlcipher/tree/msvc). Again personally I prefer the command line and compile through nmake, but I think I have seen some other similar forks with Visual Studio solutions.
As an extra note regarding windows, zetetic is offering a [commercial edition](https://www.zetetic.net/sqlcipher/buy/) with precompiled binaries, and I have no intention ever to offer the same for free or for money.

For android because at first it is not so obvious how to get libraries I included them in the [android branch](https://github.com/sjemens/qsqlcipher-qt5/tree/android) but I am not willing to keep them up to date. For that, I wrote some instructions [here](https://github.com/sjemens/sqlcipher/tree/android)

As for macOS and iOS no chance until i get mac, which does not seem to be soon.

**Comment by joenano** [comment]
I was suggesting you provide a link to the things that people need to make it work.

"SQLCipher headers and libraries should be installed" is quite ambiguous, links to where these necessary headers and libraries are found would be extremely helpful. I no longer need them as I found a [plugin ](https://github.com/devbean/QtCipherSqlitePlugin) that works out the box but might be helpful for someone in the future.
