### ISSUE TITLE
How can this plugin be installed in Windows 10? Is it possible to use in PyQt5?

### ISSUE THREAD

**Issue by amunozo** [sjemens/qsqlcipher-qt5#4]

**Comment by sjemens** [comment]
In Windows 10 as in every OS there is a Qt plugins folder. You can find it by running 
```
 qmake -query QT_INSTALL_PLUGINS
```
Just copy the qsqlicipher.dll in the sqldrivers subfolder.

It is possible to use it with PyQt5 or PySide2. Just find the plugin folder for Qt bindings in site-packages. Here is a very minimal program to get the plugin folder
```python
import sys
from PyQt5.QtCore import QLibraryInfo

print(QLibraryInfo.location(QLibraryInfo.PluginsPath))
```
Again put the qsqlcipher in the sqldrivers subfolder.

As a side note it is easier to build with msvc if you use my exp branch instead of master.

**Comment by amunozo** [comment]
And how the qsqlcipher.dll is created? Sorry for these silly questions I am very new to this world and it's being difficult. Thanks a lot for your time and work!

**Comment by sjemens** [comment]
@amunozo Can you please provide some more information about your development environment?
Have you installed some version of Qt and for which compiler?

**Comment by amunozo** [comment]
I installed Qt 5.14.1, but the command shell doesn't recognize qmake.

**Comment by sjemens** [comment]
@amunozo The easiest way is to add the bin folder like C:\Qt\5.14.1\msvc2017_64\bin to your PATH. This is pretty basic stuff. Maybe you should start by taking a look at the [Qt documentation](https://doc.qt.io/qt-5/gettingstarted.html) or the [wiki](https://wiki.qt.io/Category:HowTo). I am sorry but the issues page is not the right place for this. If you need further help send me an email and I will do my best to help you.
