### ISSUE TITLE
[Android branch] undefined reference to stderr, stdin, stdout..

### ISSUE THREAD

**Issue by faizol** [sjemens/qsqlcipher-qt5#8]
Hi, 
 I downloaded and compiled your android branch of the plugin and got into errors. The 64 bit versions of the plugin (arm64-v8a and x86_64) can only be linked against shared library of sqlcipher (libsqlcipher.so) instead of the static libsqlcipher.a. Otherwise the linker will throw undefined reference to stderr, stdin, stdout etc. 

The minimum required android API for the 64 bit version was set to 23, but I also got the same error messages if I increased the minimum API to 26.

Any pointers on how should I go about to solve this? 

TIA.

regards,
Faizol

**Comment by sjemens** [comment]
@faizol Can you tell me a little bit about your build environment like which Qt version you are using and in which OS you try to cross compile?

**Comment by faizol** [comment]
Sorry for didn't include earlier the details about the build environment.
My build system is as the following;
OS : Fedora 33
Qt : 5.15.1
Target OS : Android 
                  - with API = 19 for x86 and armeabi-v7a, both compiled with no problem.
                  - with API = 23 for x86_64 and arm64-v8a, both failed with undefined reference to stderr, stdin,  stdout when using static libsqlcipher.a lib. Both can be linked with shared version of sqlcipher lib.

**Comment by sjemens** [comment]
@faizol There is a new [android-5,15 branch](https://github.com/sjemens/qsqlcipher-qt5/tree/android-5.15).
The included static libraries are built with NDK r21.1.6352462 . SQLCipher is version 4.4.0 and OpenSSL is version 1.1.1h
The ANDROID_SDK_VERSION=21 for all ANDROID_ABIS.
You will probably have no problem if you use NDK > r20b
The undefined reference to stderr is a rather common error when linking with a newer version of NDK to an older static library. The reason is that in stdio.h, stderr have different names depending on NDK version. See [issue](https://github.com/android/ndk/issues/272)

Let me know if this works for you.

**Comment by faizol** [comment]
Hi,
The new branch solved the problem. 
Thank you.
